openapi: 3.0.1
info:
  contact:
    email: support@cqse.eu
  description: |
    The Teamscale Polarion plugin allows a more efficient integration of Polarion into Teamscale.
    The plugin performs many calculations within the Polarion server, that normally would require multiple SOAP calls.
  title: Teamscale Polarion Plugin REST API
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /api/teamscale/{project}/{space}/{module}/work-item-updates:
    parameters:
      - name: project
        in: path
        required: true
        schema:
          type: string
        description: |
          Polarion project to read requirements from
        example: drivepilot
      - name: space
        in: path
        required: true
        schema:
          type: string
        description: |
          Location (relative to “modules” folder of the Polarion project) containing the specification.
        example: Requirements
      - name: module
        in: path
        required: true
        schema:
          type: string
        description: |
          Module/document containing the work items.
        example: Project Scope
    get:
      description: |
        Get all work item updates since the lastUpdate revision number.
        The updates must also include all link changes for each link side, independent on which side the link was changed.
        For example, if the item ABC added a link to item DEF, the result must contain an update for ABC and DEF respectively.
        An exception applies if the other link side is not included in the general bounds (e.g. different project, in recycle bin etc.).
      parameters:
        - name: lastUpdate
          in: query
          schema:
            type: integer
          description: |
            Revision number of the last retrieval.
            All updates after this revision shall be included in the response.
            If omitted, all updates should be present since revision 1.
        - name: endRevision
          in: query
          schema:
            type: integer
          description: |
            Revision number that indicates the end revision the server should look for. All changes up to that revision (included). If not included in the request the server will consider changes up to the latest revision.          
        - name: includedWorkItemTypes
          in: query
          schema:
            type: array
            items:
              type: string
          description: |
            List of possible types, the items included in the result can have. If empty, all items of all types should be included.
        - name: includedWorkItemCustomFields
          in: query
          schema:
            type: array
            items:
              type: string
          description: |
            List of work item custom fields that should be included in the result. If empty, no custom fields should be present.
        - name: includedWorkItemLinkRoles
          in: query
          schema:
            type: array
            items:
              type: string
          description: |
            List of possible work item link roles that should be included in the result. If empty, no work item links should be included.
      responses:
        200:
          description: Successful update
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkItemUpdateResponse'
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found 
components:
  schemas:
    WorkItemUpdateResponse:
      type: object
      description: |
        Response type for work item update retrieval.
      properties:
        allItemsIds:
          type: array
          description: Ids of all items valid in the document at its latest revision. Useful for the client to run a diff check to detect deletions.
          items:
              type: string
        workItems:
          type: array
          description: The work items and their changes included in this batch.
          items:
            $ref: '#/components/schemas/WorkItem'
      required:
        - allItemsIds
        - workItems
    WorkItem:
      type: object
      description: |
        Describes the state of a single work item at its latest revision up to the 'endRevision' number passed in the request, if present, otherwise at its latest revision (if endReivision is not present).
      required:
        - id
        - updateType
        - revision
      properties:
        id:
          example: EL-45
          type: string
        revision:
          example: '1234'
          type: string
        updateType:
          type: string
          enum:
            - UPDATE
            - DELETE
        created:
          type: string
          example: '1970-01-01T00:00:00Z'
          format: date-time
        description:
          type: string
          example: My text value
        dueDate:
          type: string
          example: '1970-01-01'
          format: date
        hyperlinks:
          type: array
          items:
            type: string
        initialEstimate:
          example: '5 1/2d'
          type: string
        outlineNumber:
          example: '1.11'
          type: string
        plannedEnd:
          example: '1970-01-01T00:00:00Z'
          format: date-time
          type: string
        plannedStart:
          example: '1970-01-01T00:00:00Z'
          format: date-time
          type: string
        plannedIn:
          type: array
          items:
            type: string          
        priority:
          example: '90.0'
          type: string
        remainingEstimate:
          example: '5 1/2d'
          type: string
        resolution:
          example: 'done'
          type: string
        resolvedOn:
          example: '1970-01-01T00:00:00Z'
          format: date-time
          type: string
        severity:
          example: 'blocker'
          type: string
        status:
          example: 'open'
          type: string
        timeSpent:
          example: '5 1/2d'
          type: string
        title:
          example: 'a work item title'
          type: string
        type:
          example: 'task'
          type: string
        updated:
          example: '1970-01-01T00:00:00Z'
          format: date-time
          type: string
        moduleId:
          example: 'Requirements'
          type: string 
        moduleTitle:
          example: 'Requirements'
          type: string   
        projectId:
          example: 'e-library'
          type: string 
        assignees:
          type: array
          items:
            type: string    
        attachments:
          type: array
          items:
            type: string  
        author:
          example: 'ted_lasso'
          type: string
        categories:
          type: array
          items:
            type: string  
        comments:
          type: array
          items:
            type: string  
        watchers:
          type: array
          items:
            type: string             
        customFields:
          type: array
          items: 
            $ref: '#/components/schemas/CustomFieldValue'
          description: Contains all custom fields            
        linkedWorkItems:
          type: array
          items:
            type: object
            properties:
              id:
                example: 'EL-109'
                type: string
              linkRoleId:
                example: 'parent'
                type: string
              linkRoleName:
                example: 'has parent'
                type: string
              linkDirection:
                example: 'OUT'
                type: string
                enum:
                  - IN
                  - OUT
        workItemChanges:
          type: array
          items: 
            $ref: '#/components/schemas/WorkItemChange'
          description: Collection of changes for the work item grouped by revision number
    CustomFieldValue:
      type: object
      description: Value of the custom field. Does not have an explicit type, as this depends on the custom field definition    
    WorkItemChange:
      type: object
      required:
        - revision
        - fieldChanges
      properties:
        revision:
          type: string
          example: '123'
          description: Revision of which the work item was updated
        fieldChanges:
          type: array
          items: 
            oneOf:
            - $ref: '#/components/schemas/FieldChange'
            - $ref: '#/components/schemas/LinkFieldChange'
        valueBefore:
            description: Value before the change
        valueAfter:
            description: Value after the change
    FieldChange:
      type: object
      description: Object that represents a field change (fieldDiff)
      properties:
        fieldName:
          type: string
          example: 'title'
        oneOfTheFollowing:
          oneOf:
            - properties:
                fieldValueBefore:
                  type: string
                  example: 'Borrow a Book'
                fieldValueAfter:
                  type: string
                  example: 'Reserve a Book'
            - properties:
                elementsAdded:
                  type: array
                  items: 
                    type: string
            - properties:
                elementsRemoved:
                  type: array
                  items: 
                    type: string       
    LinkFieldChange:
      type: object
      properties:
        linkRoleId:
          type: string
          example: 'parent'
        linkRoleName:
          type: string
          example: 'has parent'
        linkRoleDirection:
          type: string
          enum:
            - IN
            - OUT
        fieldName:
          type: string
          example: 'linkedWorkItems'        
        oneOfTheFollowing:
          oneOf:
            - properties:
                elementsAdded:
                  type: array
                  items: 
                    type: string
            - properties:
                elementsRemoved:
                  type: array
                  items: 
                    type: string  
